/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const CompletionStop: core.serialization.Schema<serializers.CompletionStop.Raw, OpenAI.CompletionStop> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
    ]);

export declare namespace CompletionStop {
    type Raw = string | string[];
}
