/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateCompletionResponseChunk: core.serialization.ObjectSchema<
    serializers.CreateCompletionResponseChunk.Raw,
    OpenAI.CreateCompletionResponseChunk
> = core.serialization.object({
    id: core.serialization.string(),
    object: core.serialization.string(),
    created: core.serialization.number(),
    model: core.serialization.string(),
    choices: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).CompletionChoice)
    ),
});

export declare namespace CreateCompletionResponseChunk {
    interface Raw {
        id: string;
        object: string;
        created: number;
        model: string;
        choices: serializers.CompletionChoice.Raw[];
    }
}
