/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const Prompt: core.serialization.Schema<serializers.Prompt.Raw, OpenAI.Prompt> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
        core.serialization.list(core.serialization.number()),
        core.serialization.list(core.serialization.list(core.serialization.number())),
    ]);

export declare namespace Prompt {
    type Raw = string | string[] | number[] | number[][];
}
