/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/openai";

export interface CreateClassificationResponse {
    object?: string;
    model?: string;
    searchModel?: string;
    completion?: string;
    label?: string;
    selectedExamples?: OpenAiApi.SelectedExample[];
}
