/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/openai";

export interface CreateSearchResponse {
    object?: string;
    model?: string;
    data?: OpenAiApi.SearchData[];
}
