/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface CreateSearchResponse {
    object?: string;
    model?: string;
    data?: OpenAI.SearchData[];
}
