/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CategoryScores: core.serialization.ObjectSchema<serializers.CategoryScores.Raw, OpenAiApi.CategoryScores> =
    core.serialization.object({
        hate: core.serialization.number(),
        hateThreatening: core.serialization.property("hate/threatening", core.serialization.number()),
        selfHarm: core.serialization.property("self-harm", core.serialization.number()),
        sexual: core.serialization.number(),
        sexualMinors: core.serialization.property("sexual/minors", core.serialization.number()),
        violence: core.serialization.number(),
        violenceGraphic: core.serialization.property("violence/graphic", core.serialization.number()),
    });

export declare namespace CategoryScores {
    interface Raw {
        hate: number;
        "hate/threatening": number;
        "self-harm": number;
        sexual: number;
        "sexual/minors": number;
        violence: number;
        "violence/graphic": number;
    }
}
