/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateModerationRequest: core.serialization.ObjectSchema<
    serializers.CreateModerationRequest.Raw,
    OpenAiApi.CreateModerationRequest
> = core.serialization.object({
    model: core.serialization.string().optional(),
});

export declare namespace CreateModerationRequest {
    interface Raw {
        model?: string | null;
    }
}
