/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface CreateModerationResponse {
    id: string;
    model: string;
    results: OpenAI.ModerationResults[];
}
