/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface ModerationResults {
    flagged: boolean;
    categories: OpenAI.Categories;
    categoryScores: OpenAI.CategoryScores;
}
