/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/open-ai";

export interface CreateEditResponse {
    object: string;
    created: number;
    choices: OpenAiApi.EditChoice[];
    usage: OpenAiApi.EditUsage;
}
