/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface CreateEditResponse {
    object: string;
    created: number;
    choices: OpenAI.EditChoice[];
    usage: OpenAI.EditUsage;
}
