/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface EditChoice {
    text?: string;
    index?: number;
    logprobs?: OpenAI.LogProbs;
    finishReason?: string;
}
