/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/open-ai";

export interface CreateModerationResponse {
    id: string;
    model: string;
    results: OpenAiApi.ModerationResults[];
}
