/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/open-ai";

export interface CreateEmbeddingResponse {
    object: string;
    model: string;
    data: OpenAiApi.EmbedData[];
    usage: OpenAiApi.EmbedUsage;
}
