/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class OpenAITimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, OpenAITimeoutError.prototype);
    }
}
