/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/openai";

export interface ImagesResponse {
    created: number;
    data: OpenAiApi.ImageData[];
}
