/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const ExampleItems: core.serialization.ObjectSchema<serializers.ExampleItems.Raw, OpenAiApi.ExampleItems> =
    core.serialization.object({
        items: core.serialization.lazy(async () => (await import("../../..")).QuestionAnswer),
    });

export declare namespace ExampleItems {
    interface Raw {
        items: serializers.QuestionAnswer.Raw;
    }
}
