/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const QuestionAnswer: core.serialization.Schema<serializers.QuestionAnswer.Raw, OpenAiApi.QuestionAnswer> =
    core.serialization.list(core.serialization.string());

export declare namespace QuestionAnswer {
    type Raw = string[];
}
