/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const SelectedDocument: core.serialization.ObjectSchema<
    serializers.SelectedDocument.Raw,
    OpenAI.SelectedDocument
> = core.serialization.object({
    document: core.serialization.number().optional(),
    text: core.serialization.string().optional(),
});

export declare namespace SelectedDocument {
    interface Raw {
        document?: number | null;
        text?: string | null;
    }
}
