/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const ListFineTuneEventsResponse: core.serialization.ObjectSchema<
    serializers.ListFineTuneEventsResponse.Raw,
    OpenAI.ListFineTuneEventsResponse
> = core.serialization.object({
    object: core.serialization.string(),
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).FineTuneEvent)),
});

export declare namespace ListFineTuneEventsResponse {
    interface Raw {
        object: string;
        data: serializers.FineTuneEvent.Raw[];
    }
}
