/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AuthorRole = "system" | "user" | "assistant";

export const AuthorRole = {
    System: "system",
    User: "user",
    Assistant: "assistant",
} as const;
