/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * These are the models currently supported.
 */
export type ChatModel = "gpt-3.5-turbo" | "gpt-3.5-turbo-0301";

export const ChatModel = {
    Gpt35Turbo: "gpt-3.5-turbo",
    Gpt35Turbo0301: "gpt-3.5-turbo-0301",
} as const;
