/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/openai";

export interface ChatCompletionResponseMessage {
    /** The role of the author of this message. */
    role: OpenAiApi.AuthorRole;
    /** The contents of the message */
    content: string;
}
