/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface ChatCompletionRequestMessage {
    /** The role of the author of this message. */
    role: OpenAI.AuthorRole;
    /** The contents of the message */
    content: string;
    /** The name of the user in a multi-user chat */
    name?: string;
}
