/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface ChatItemsDelta {
    role?: OpenAI.AuthorRole;
    content?: string;
}
