/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../../../core";

export const CreateTranscriptionResponse: core.serialization.ObjectSchema<
    serializers.audio.CreateTranscriptionResponse.Raw,
    OpenAiApi.audio.CreateTranscriptionResponse
> = core.serialization.object({
    text: core.serialization.string(),
});

export declare namespace CreateTranscriptionResponse {
    interface Raw {
        text: string;
    }
}
