/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateImageRequest: core.serialization.ObjectSchema<
    serializers.CreateImageRequest.Raw,
    OpenAiApi.CreateImageRequest
> = core.serialization.object({
    prompt: core.serialization.string(),
    n: core.serialization.number().optional(),
    size: core.serialization.lazy(async () => (await import("../../..")).Size).optional(),
    responseFormat: core.serialization.property(
        "response_format",
        core.serialization.lazy(async () => (await import("../../..")).ImageFormat).optional()
    ),
    user: core.serialization.string().optional(),
});

export declare namespace CreateImageRequest {
    interface Raw {
        prompt: string;
        n?: number | null;
        size?: serializers.Size.Raw | null;
        response_format?: serializers.ImageFormat.Raw | null;
        user?: string | null;
    }
}
