/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Transcriptions } from "../resources/transcriptions/client/Client";
import { Translations } from "../resources/translations/client/Client";

export declare namespace Audio {
    interface Options {
        environment?: environments.OpenAiApiEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class Audio {
    constructor(private readonly options: Audio.Options) {}

    private _transcriptions: Transcriptions | undefined;

    public get transcriptions(): Transcriptions {
        return (this._transcriptions ??= new Transcriptions(this.options));
    }

    private _translations: Translations | undefined;

    public get translations(): Translations {
        return (this._translations ??= new Translations(this.options));
    }
}
