/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateSearchRequest: core.serialization.ObjectSchema<
    serializers.CreateSearchRequest.Raw,
    OpenAiApi.CreateSearchRequest
> = core.serialization.object({
    query: core.serialization.string(),
    documents: core.serialization.list(core.serialization.string()).optional(),
    file: core.serialization.string().optional(),
    maxRerank: core.serialization.property("max_rerank", core.serialization.number().optional()),
    returnMetadata: core.serialization.property("return_metadata", core.serialization.boolean().optional()),
    user: core.serialization.string().optional(),
});

export declare namespace CreateSearchRequest {
    interface Raw {
        query: string;
        documents?: string[] | null;
        file?: string | null;
        max_rerank?: number | null;
        return_metadata?: boolean | null;
        user?: string | null;
    }
}
