/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const EngineId: core.serialization.Schema<serializers.EngineId.Raw, OpenAI.EngineId> =
    core.serialization.string();

export declare namespace EngineId {
    type Raw = string;
}
