/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const Categories: core.serialization.ObjectSchema<serializers.Categories.Raw, OpenAI.Categories> =
    core.serialization.object({
        hate: core.serialization.boolean(),
        hateThreatening: core.serialization.property("hate/threatening", core.serialization.boolean()),
        selfHarm: core.serialization.property("self-harm", core.serialization.boolean()),
        sexual: core.serialization.boolean(),
        sexualMinors: core.serialization.property("sexual/minors", core.serialization.boolean()),
        violence: core.serialization.boolean(),
        violenceGraphic: core.serialization.property("violence/graphic", core.serialization.boolean()),
    });

export declare namespace Categories {
    interface Raw {
        hate: boolean;
        "hate/threatening": boolean;
        "self-harm": boolean;
        sexual: boolean;
        "sexual/minors": boolean;
        violence: boolean;
        "violence/graphic": boolean;
    }
}
