/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateModerationInput: core.serialization.Schema<
    serializers.CreateModerationInput.Raw,
    OpenAiApi.CreateModerationInput
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace CreateModerationInput {
    type Raw = string | string[];
}
