/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateModerationResponse: core.serialization.ObjectSchema<
    serializers.CreateModerationResponse.Raw,
    OpenAI.CreateModerationResponse
> = core.serialization.object({
    id: core.serialization.string(),
    model: core.serialization.string(),
    results: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ModerationResults)
    ),
});

export declare namespace CreateModerationResponse {
    interface Raw {
        id: string;
        model: string;
        results: serializers.ModerationResults.Raw[];
    }
}
