/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const ModerationResults: core.serialization.ObjectSchema<
    serializers.ModerationResults.Raw,
    OpenAI.ModerationResults
> = core.serialization.object({
    flagged: core.serialization.boolean(),
    categories: core.serialization.lazyObject(async () => (await import("../../..")).Categories),
    categoryScores: core.serialization.property(
        "category_scores",
        core.serialization.lazyObject(async () => (await import("../../..")).CategoryScores)
    ),
});

export declare namespace ModerationResults {
    interface Raw {
        flagged: boolean;
        categories: serializers.Categories.Raw;
        category_scores: serializers.CategoryScores.Raw;
    }
}
