/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const FileId: core.serialization.Schema<serializers.FileId.Raw, OpenAI.FileId> = core.serialization.string();

export declare namespace FileId {
    type Raw = string;
}
