/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CompletionUsage: core.serialization.ObjectSchema<
    serializers.CompletionUsage.Raw,
    OpenAiApi.CompletionUsage
> = core.serialization.object({
    promptTokens: core.serialization.property("prompt_tokens", core.serialization.number()),
    completionTokens: core.serialization.property("completion_tokens", core.serialization.number()),
    totalTokens: core.serialization.property("total_tokens", core.serialization.number()),
});

export declare namespace CompletionUsage {
    interface Raw {
        prompt_tokens: number;
        completion_tokens: number;
        total_tokens: number;
    }
}
