/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateCompletionRequest: core.serialization.ObjectSchema<
    serializers.CreateCompletionRequest.Raw,
    OpenAiApi.CreateCompletionRequest
> = core.serialization.object({
    model: core.serialization.string(),
    suffix: core.serialization.string().optional(),
    maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
    temperature: core.serialization.number().optional(),
    topP: core.serialization.property("top_p", core.serialization.number().optional()),
    n: core.serialization.number().optional(),
    stream: core.serialization.boolean().optional(),
    logprobs: core.serialization.number().optional(),
    echo: core.serialization.boolean().optional(),
    presencePenalty: core.serialization.property("presence_penalty", core.serialization.number().optional()),
    frequencyPenalty: core.serialization.property("frequency_penalty", core.serialization.number().optional()),
    bestOf: core.serialization.property("best_of", core.serialization.number().optional()),
    logitBias: core.serialization.property(
        "logit_bias",
        core.serialization.record(core.serialization.string(), core.serialization.number().optional()).optional()
    ),
    user: core.serialization.string().optional(),
});

export declare namespace CreateCompletionRequest {
    interface Raw {
        model: string;
        suffix?: string | null;
        max_tokens?: number | null;
        temperature?: number | null;
        top_p?: number | null;
        n?: number | null;
        stream?: boolean | null;
        logprobs?: number | null;
        echo?: boolean | null;
        presence_penalty?: number | null;
        frequency_penalty?: number | null;
        best_of?: number | null;
        logit_bias?: Record<string, number | null | undefined> | null;
        user?: string | null;
    }
}
