/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/open-ai";

export interface CreateCompletionResponse {
    id: string;
    object: string;
    created: number;
    model: string;
    choices: OpenAiApi.CompletionChoice[];
    usage?: OpenAiApi.CompletionUsage;
}
