/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const DeleteFileResponse: core.serialization.ObjectSchema<
    serializers.DeleteFileResponse.Raw,
    OpenAiApi.DeleteFileResponse
> = core.serialization.object({
    id: core.serialization.string(),
    object: core.serialization.string(),
    deleted: core.serialization.boolean(),
});

export declare namespace DeleteFileResponse {
    interface Raw {
        id: string;
        object: string;
        deleted: boolean;
    }
}
