/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateEditResponse: core.serialization.ObjectSchema<
    serializers.CreateEditResponse.Raw,
    OpenAI.CreateEditResponse
> = core.serialization.object({
    object: core.serialization.string(),
    created: core.serialization.number(),
    choices: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).EditChoice)),
    usage: core.serialization.lazyObject(async () => (await import("../../..")).EditUsage),
});

export declare namespace CreateEditResponse {
    interface Raw {
        object: string;
        created: number;
        choices: serializers.EditChoice.Raw[];
        usage: serializers.EditUsage.Raw;
    }
}
