/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../../../core";

export const CreateTranslationRequest: core.serialization.ObjectSchema<
    serializers.audio.CreateTranslationRequest.Raw,
    OpenAiApi.audio.CreateTranslationRequest
> = core.serialization.object({
    file: core.serialization.lazy(async () => (await import("../../../../..")).AudioFile),
    model: core.serialization.string(),
    prompt: core.serialization.string().optional(),
    responseFormat: core.serialization.property(
        "response_format",
        core.serialization.lazy(async () => (await import("../../../../..")).FileFormat).optional()
    ),
    temperature: core.serialization.number().optional(),
});

export declare namespace CreateTranslationRequest {
    interface Raw {
        file: serializers.AudioFile.Raw;
        model: string;
        prompt?: string | null;
        response_format?: serializers.FileFormat.Raw | null;
        temperature?: number | null;
    }
}
