/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const DeleteModelResponse: core.serialization.ObjectSchema<
    serializers.DeleteModelResponse.Raw,
    OpenAiApi.DeleteModelResponse
> = core.serialization.object({
    id: core.serialization.string(),
    object: core.serialization.string(),
    deleted: core.serialization.boolean(),
});

export declare namespace DeleteModelResponse {
    interface Raw {
        id: string;
        object: string;
        deleted: boolean;
    }
}
