/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const ModelId: core.serialization.Schema<serializers.ModelId.Raw, OpenAI.ModelId> = core.serialization.string();

export declare namespace ModelId {
    type Raw = string;
}
