/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateAnswerRequest: core.serialization.ObjectSchema<
    serializers.CreateAnswerRequest.Raw,
    OpenAiApi.CreateAnswerRequest
> = core.serialization.object({
    model: core.serialization.string(),
    question: core.serialization.string(),
    examples: core.serialization.list(core.serialization.list(core.serialization.string())),
    examplesContext: core.serialization.property("examples_context", core.serialization.string()),
    documents: core.serialization.list(core.serialization.string()).optional(),
    file: core.serialization.string().optional(),
    searchModel: core.serialization.property("search_model", core.serialization.string().optional()),
    maxRerank: core.serialization.property("max_rerank", core.serialization.number().optional()),
    temperature: core.serialization.number().optional(),
    logprobs: core.serialization.number().optional(),
    maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
    n: core.serialization.number().optional(),
    logitBias: core.serialization.property(
        "logit_bias",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    returnMetadata: core.serialization.property("return_metadata", core.serialization.boolean().optional()),
    returnPrompt: core.serialization.property("return_prompt", core.serialization.boolean().optional()),
    expand: core.serialization.list(core.serialization.unknown()).optional(),
    user: core.serialization.string().optional(),
});

export declare namespace CreateAnswerRequest {
    interface Raw {
        model: string;
        question: string;
        examples: string[][];
        examples_context: string;
        documents?: string[] | null;
        file?: string | null;
        search_model?: string | null;
        max_rerank?: number | null;
        temperature?: number | null;
        logprobs?: number | null;
        max_tokens?: number | null;
        n?: number | null;
        logit_bias?: Record<string, unknown> | null;
        return_metadata?: boolean | null;
        return_prompt?: boolean | null;
        expand?: unknown[] | null;
        user?: string | null;
    }
}
