/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateAnswerResponse: core.serialization.ObjectSchema<
    serializers.CreateAnswerResponse.Raw,
    OpenAiApi.CreateAnswerResponse
> = core.serialization.object({
    object: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
    searchModel: core.serialization.property("search_model", core.serialization.string().optional()),
    completion: core.serialization.string().optional(),
    answers: core.serialization.list(core.serialization.string()).optional(),
    selectedDocuments: core.serialization.property(
        "selected_documents",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).SelectedDocument))
            .optional()
    ),
});

export declare namespace CreateAnswerResponse {
    interface Raw {
        object?: string | null;
        model?: string | null;
        search_model?: string | null;
        completion?: string | null;
        answers?: string[] | null;
        selected_documents?: serializers.SelectedDocument.Raw[] | null;
    }
}
