/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The format in which the generated images are returned.
 */
export type ImageFormat = "url" | "b64_json";

export const ImageFormat = {
    Url: "url",
    B64Json: "b64_json",
} as const;
