/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The size of the generated images.
 */
export type Size = "256x256" | "512x512" | "1024x1024";

export const Size = {
    TwoHundredFiftySix: "256x256",
    FiveHundredTwelve: "512x512",
    OneThousandTwentyFour: "1024x1024",
} as const;
