/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface FineTune {
    id: string;
    object: string;
    createdAt: number;
    updatedAt: number;
    model: string;
    fineTunedModel?: string;
    organizationId: string;
    status: string;
    hyperparams: Record<string, unknown>;
    trainingFiles: OpenAI.OpenAiFile[];
    validationFiles: OpenAI.OpenAiFile[];
    resultFiles: OpenAI.OpenAiFile[];
    events?: OpenAI.FineTuneEvent[];
}
