/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/openai";

export interface FineTune {
    id: string;
    object: string;
    createdAt: number;
    updatedAt: number;
    model: string;
    fineTunedModel?: string;
    organizationId: string;
    status: string;
    hyperparams: Record<string, unknown>;
    trainingFiles: OpenAiApi.OpenAiFile[];
    validationFiles: OpenAiApi.OpenAiFile[];
    resultFiles: OpenAiApi.OpenAiFile[];
    events?: OpenAiApi.FineTuneEvent[];
}
