/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const ImageFormat: core.serialization.Schema<serializers.ImageFormat.Raw, OpenAiApi.ImageFormat> =
    core.serialization.enum_(["url", "b64_json"]);

export declare namespace ImageFormat {
    type Raw = "url" | "b64_json";
}
