/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const ImageData: core.serialization.ObjectSchema<serializers.ImageData.Raw, OpenAI.ImageData> =
    core.serialization.object({
        url: core.serialization.string().optional(),
        b64Json: core.serialization.property("b64_json", core.serialization.string().optional()),
    });

export declare namespace ImageData {
    interface Raw {
        url?: string | null;
        b64_json?: string | null;
    }
}
