/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const ImagesResponse: core.serialization.ObjectSchema<serializers.ImagesResponse.Raw, OpenAI.ImagesResponse> =
    core.serialization.object({
        created: core.serialization.number(),
        data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ImageData)),
    });

export declare namespace ImagesResponse {
    interface Raw {
        created: number;
        data: serializers.ImageData.Raw[];
    }
}
