/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const Size: core.serialization.Schema<serializers.Size.Raw, OpenAI.Size> = core.serialization.enum_([
    "256x256",
    "512x512",
    "1024x1024",
]);

export declare namespace Size {
    type Raw = "256x256" | "512x512" | "1024x1024";
}
