/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateClassificationRequest: core.serialization.ObjectSchema<
    serializers.CreateClassificationRequest.Raw,
    OpenAiApi.CreateClassificationRequest
> = core.serialization.object({
    model: core.serialization.string(),
    query: core.serialization.string(),
    examples: core.serialization.list(core.serialization.list(core.serialization.string())).optional(),
    file: core.serialization.string().optional(),
    labels: core.serialization.list(core.serialization.string()).optional(),
    searchModel: core.serialization.property("search_model", core.serialization.string().optional()),
    temperature: core.serialization.number().optional(),
    logprobs: core.serialization.number().optional(),
    maxExamples: core.serialization.property("max_examples", core.serialization.number().optional()),
    logitBias: core.serialization.property(
        "logit_bias",
        core.serialization.record(core.serialization.string(), core.serialization.number().optional()).optional()
    ),
    returnPrompt: core.serialization.property("return_prompt", core.serialization.boolean().optional()),
    returnMetadata: core.serialization.property("return_metadata", core.serialization.boolean().optional()),
    expand: core.serialization.list(core.serialization.unknown()).optional(),
    user: core.serialization.string().optional(),
});

export declare namespace CreateClassificationRequest {
    interface Raw {
        model: string;
        query: string;
        examples?: string[][] | null;
        file?: string | null;
        labels?: string[] | null;
        search_model?: string | null;
        temperature?: number | null;
        logprobs?: number | null;
        max_examples?: number | null;
        logit_bias?: Record<string, number | null | undefined> | null;
        return_prompt?: boolean | null;
        return_metadata?: boolean | null;
        expand?: unknown[] | null;
        user?: string | null;
    }
}
