/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const SelectedExample: core.serialization.ObjectSchema<
    serializers.SelectedExample.Raw,
    OpenAiApi.SelectedExample
> = core.serialization.object({
    document: core.serialization.number().optional(),
    text: core.serialization.string().optional(),
    label: core.serialization.string().optional(),
});

export declare namespace SelectedExample {
    interface Raw {
        document?: number | null;
        text?: string | null;
        label?: string | null;
    }
}
