/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateClassificationResponse: core.serialization.ObjectSchema<
    serializers.CreateClassificationResponse.Raw,
    OpenAiApi.CreateClassificationResponse
> = core.serialization.object({
    object: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
    searchModel: core.serialization.property("search_model", core.serialization.string().optional()),
    completion: core.serialization.string().optional(),
    label: core.serialization.string().optional(),
    selectedExamples: core.serialization.property(
        "selected_examples",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).SelectedExample))
            .optional()
    ),
});

export declare namespace CreateClassificationResponse {
    interface Raw {
        object?: string | null;
        model?: string | null;
        search_model?: string | null;
        completion?: string | null;
        label?: string | null;
        selected_examples?: serializers.SelectedExample.Raw[] | null;
    }
}
