/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAiApi } from "@fern-api/openai";

/**
 * @example
 *     {
 *         items: ["'What is the capital of Canada?', 'Ottawa'", "'Which province is Ottawa in?', 'Ontario'"]
 *     }
 */
export interface ExampleItems {
    items: OpenAiApi.QuestionAnswer;
}
