/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateTranscriptionResponse: core.serialization.ObjectSchema<
    serializers.CreateTranscriptionResponse.Raw,
    OpenAI.CreateTranscriptionResponse
> = core.serialization.object({
    text: core.serialization.string(),
});

export declare namespace CreateTranscriptionResponse {
    interface Raw {
        text: string;
    }
}
