/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const ListFineTunesResponse: core.serialization.ObjectSchema<
    serializers.ListFineTunesResponse.Raw,
    OpenAiApi.ListFineTunesResponse
> = core.serialization.object({
    object: core.serialization.string(),
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).FineTune)),
});

export declare namespace ListFineTunesResponse {
    interface Raw {
        object: string;
        data: serializers.FineTune.Raw[];
    }
}
