/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../../core";

export const CreateEmbeddingRequest: core.serialization.Schema<
    serializers.CreateEmbeddingRequest.Raw,
    OpenAiApi.CreateEmbeddingRequest
> = core.serialization.object({
    model: core.serialization.string(),
    input: core.serialization.lazy(async () => (await import("../../../..")).EmbeddingInput),
    user: core.serialization.string().optional(),
});

export declare namespace CreateEmbeddingRequest {
    interface Raw {
        model: string;
        input: serializers.EmbeddingInput.Raw;
        user?: string | null;
    }
}
