/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const AuthorRole: core.serialization.Schema<serializers.AuthorRole.Raw, OpenAI.AuthorRole> =
    core.serialization.enum_(["system", "user", "assistant"]);

export declare namespace AuthorRole {
    type Raw = "system" | "user" | "assistant";
}
