/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const ChatModel: core.serialization.Schema<serializers.ChatModel.Raw, OpenAI.ChatModel> =
    core.serialization.enum_(["gpt-3.5-turbo", "gpt-3.5-turbo-0301"]);

export declare namespace ChatModel {
    type Raw = "gpt-3.5-turbo" | "gpt-3.5-turbo-0301";
}
