/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const ChatCompletionRequestMessage: core.serialization.ObjectSchema<
    serializers.ChatCompletionRequestMessage.Raw,
    OpenAiApi.ChatCompletionRequestMessage
> = core.serialization.object({
    role: core.serialization.lazy(async () => (await import("../../..")).AuthorRole),
    content: core.serialization.string(),
    name: core.serialization.string().optional(),
});

export declare namespace ChatCompletionRequestMessage {
    interface Raw {
        role: serializers.AuthorRole.Raw;
        content: string;
        name?: string | null;
    }
}
