/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const ChatItemsChunk: core.serialization.ObjectSchema<serializers.ChatItemsChunk.Raw, OpenAI.ChatItemsChunk> =
    core.serialization.object({
        delta: core.serialization.lazyObject(async () => (await import("../../..")).ChatItemsDelta),
        index: core.serialization.number(),
        finishReason: core.serialization.property("finish_reason", core.serialization.string().optional()),
    });

export declare namespace ChatItemsChunk {
    interface Raw {
        delta: serializers.ChatItemsDelta.Raw;
        index: number;
        finish_reason?: string | null;
    }
}
