/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateChatCompletionResponseChunk: core.serialization.ObjectSchema<
    serializers.CreateChatCompletionResponseChunk.Raw,
    OpenAI.CreateChatCompletionResponseChunk
> = core.serialization.object({
    id: core.serialization.string(),
    object: core.serialization.string(),
    created: core.serialization.number(),
    model: core.serialization.string(),
    choices: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ChatItemsChunk)
    ),
});

export declare namespace CreateChatCompletionResponseChunk {
    interface Raw {
        id: string;
        object: string;
        created: number;
        model: string;
        choices: serializers.ChatItemsChunk.Raw[];
    }
}
