/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const CreateChatCompletionResponse: core.serialization.ObjectSchema<
    serializers.CreateChatCompletionResponse.Raw,
    OpenAiApi.CreateChatCompletionResponse
> = core.serialization.object({
    id: core.serialization.string(),
    object: core.serialization.string(),
    created: core.serialization.number(),
    model: core.serialization.string(),
    choices: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ChatItems)),
    usage: core.serialization.lazyObject(async () => (await import("../../..")).ChatUsage).optional(),
});

export declare namespace CreateChatCompletionResponse {
    interface Raw {
        id: string;
        object: string;
        created: number;
        model: string;
        choices: serializers.ChatItems.Raw[];
        usage?: serializers.ChatUsage.Raw | null;
    }
}
