/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { OpenAI } from "@fern-api/openai";

export interface ListModelsResponse {
    object: string;
    data: OpenAI.Model[];
}
