/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AudioFile = "mp3" | "mp4" | "mpeg" | "mpga" | "m4a" | "wav" | "webm";

export const AudioFile = {
    Mp3: "mp3",
    Mp4: "mp4",
    Mpeg: "mpeg",
    Mpga: "mpga",
    M4A: "m4a",
    Wav: "wav",
    Webm: "webm",
} as const;
