/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FileFormat = "json" | "text" | "srt" | "verbose_json" | "vtt";

export const FileFormat = {
    Json: "json",
    Text: "text",
    Srt: "srt",
    VerboseJson: "verbose_json",
    Vtt: "vtt",
} as const;
