/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Answers } from "./api/resources/answers/client/Client";
import { Classifications } from "./api/resources/classifications/client/Client";
import { Completions } from "./api/resources/completions/client/Client";
import { Edits } from "./api/resources/edits/client/Client";
import { Embeddings } from "./api/resources/embeddings/client/Client";
import { Engines } from "./api/resources/engines/client/Client";
import { Files } from "./api/resources/files/client/Client";
import { FineTunes } from "./api/resources/fineTunes/client/Client";
import { Images } from "./api/resources/images/client/Client";
import { Models } from "./api/resources/models/client/Client";
import { Moderations } from "./api/resources/moderations/client/Client";

export declare namespace OpenAiApiClient {
    interface Options {
        environment?: environments.OpenAiApiEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class OpenAiApiClient {
    constructor(private readonly options: OpenAiApiClient.Options) {}

    private _answers: Answers | undefined;

    public get answers(): Answers {
        return (this._answers ??= new Answers(this.options));
    }

    private _classifications: Classifications | undefined;

    public get classifications(): Classifications {
        return (this._classifications ??= new Classifications(this.options));
    }

    private _completions: Completions | undefined;

    public get completions(): Completions {
        return (this._completions ??= new Completions(this.options));
    }

    private _edits: Edits | undefined;

    public get edits(): Edits {
        return (this._edits ??= new Edits(this.options));
    }

    private _embeddings: Embeddings | undefined;

    public get embeddings(): Embeddings {
        return (this._embeddings ??= new Embeddings(this.options));
    }

    private _engines: Engines | undefined;

    public get engines(): Engines {
        return (this._engines ??= new Engines(this.options));
    }

    private _files: Files | undefined;

    public get files(): Files {
        return (this._files ??= new Files(this.options));
    }

    private _fineTunes: FineTunes | undefined;

    public get fineTunes(): FineTunes {
        return (this._fineTunes ??= new FineTunes(this.options));
    }

    private _images: Images | undefined;

    public get images(): Images {
        return (this._images ??= new Images(this.options));
    }

    private _models: Models | undefined;

    public get models(): Models {
        return (this._models ??= new Models(this.options));
    }

    private _moderations: Moderations | undefined;

    public get moderations(): Moderations {
        return (this._moderations ??= new Moderations(this.options));
    }
}
