/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const OpenAiApiEnvironment = {
    Production: "https://api.openai.com/v1/",
} as const;

export type OpenAiApiEnvironment = typeof OpenAiApiEnvironment.Production;
