/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const OpenAIEnvironment = {
    Production: "https://api.openai.com/v1/",
} as const;

export type OpenAIEnvironment = typeof OpenAIEnvironment.Production;
