/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateEmbeddingRequest: core.serialization.ObjectSchema<
    serializers.CreateEmbeddingRequest.Raw,
    OpenAiApi.CreateEmbeddingRequest
> = core.serialization.object({
    model: core.serialization.string(),
    user: core.serialization.string().optional(),
});

export declare namespace CreateEmbeddingRequest {
    interface Raw {
        model: string;
        user?: string | null;
    }
}
