/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../../core";

export const CreateModerationRequest: core.serialization.Schema<
    serializers.CreateModerationRequest.Raw,
    OpenAI.CreateModerationRequest
> = core.serialization.object({
    input: core.serialization.lazy(async () => (await import("../../../..")).CreateModerationInput),
    model: core.serialization.string().optional(),
});

export declare namespace CreateModerationRequest {
    interface Raw {
        input: serializers.CreateModerationInput.Raw;
        model?: string | null;
    }
}
