/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const CreateSearchResponse: core.serialization.ObjectSchema<
    serializers.CreateSearchResponse.Raw,
    OpenAiApi.CreateSearchResponse
> = core.serialization.object({
    object: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
    data: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).SearchData))
        .optional(),
});

export declare namespace CreateSearchResponse {
    interface Raw {
        object?: string | null;
        model?: string | null;
        data?: serializers.SearchData.Raw[] | null;
    }
}
