/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/open-ai";
import * as core from "../../../../core";

export const Engine: core.serialization.ObjectSchema<serializers.Engine.Raw, OpenAiApi.Engine> =
    core.serialization.object({
        id: core.serialization.lazy(async () => (await import("../../..")).EngineId),
        object: core.serialization.string(),
        created: core.serialization.number().optional(),
        ready: core.serialization.boolean(),
    });

export declare namespace Engine {
    interface Raw {
        id: serializers.EngineId.Raw;
        object: string;
        created?: number | null;
        ready: boolean;
    }
}
