/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAI } from "@fern-api/openai";
import * as core from "../../../../core";

export const AudioFile: core.serialization.Schema<serializers.AudioFile.Raw, OpenAI.AudioFile> =
    core.serialization.enum_(["mp3", "mp4", "mpeg", "mpga", "m4a", "wav", "webm"]);

export declare namespace AudioFile {
    type Raw = "mp3" | "mp4" | "mpeg" | "mpga" | "m4a" | "wav" | "webm";
}
