/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { OpenAiApi } from "@fern-api/openai";
import * as core from "../../../../core";

export const LogProbs: core.serialization.ObjectSchema<serializers.LogProbs.Raw, OpenAiApi.LogProbs> =
    core.serialization.object({
        tokens: core.serialization.list(core.serialization.string()).optional(),
        tokenLogprobs: core.serialization.property(
            "token_logprobs",
            core.serialization.list(core.serialization.number()).optional()
        ),
        topLogprobs: core.serialization.property(
            "top_logprobs",
            core.serialization
                .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
                .optional()
        ),
        textOffset: core.serialization.property(
            "text_offset",
            core.serialization.list(core.serialization.number()).optional()
        ),
    });

export declare namespace LogProbs {
    interface Raw {
        tokens?: string[] | null;
        token_logprobs?: number[] | null;
        top_logprobs?: Record<string, unknown>[] | null;
        text_offset?: number[] | null;
    }
}
